language: go

go:
- '1.13.4'

cache:
  directories:
    - $GOPATH/pkg/mod

env:
  jobs:
    - KUBE=1.14.10
    - KUBE=1.15.7

stages:
  - lint
  - unit
  - test

before_script:
  - echo "+++ Before matrix test"
script:
  - echo "+++ Running $TRAVIS_PULL_REQUEST_SLUG vs $TRAVIS_REQUEST_SLUG"

jobs:
  include:
    - stage: unit
      if: branch = master OR type = pull_request
      services: []
      before_script:
        - echo "+++ Before include (no matrix) step"
      script: echo "+++ Linting"
      name: lint
    - script: echo "+++ Unit"
      services: []
      before_script: []
      name: unit
      env: KUBE=none

    - stage: Publishing
      if: branch = master OR (type = pull_request AND head_repo = repo)
      install: []
      before_script: []
      before_deploy:
        - echo "+++ Before deploy"
        - git fetch --unshallow
        - git rev-list --first-parent --count HEAD
      script: echo "+++ Publishing image/chart for $TRAVIS_PULL_REQUEST"
      deploy:
        provider: script
        script:
          echo "+++ Deploy make publish-image deploy-helm-repo..."
        skip_cleanup: true
        on:
          branch: master
