language: go

go:
- '1.13.4'

cache:
  directories:
    - $GOPATH/pkg/mod

env:
  jobs:
    - KUBE=1.14.10
    - KUBE=1.15.7

stages:
  - lint
  - unit
  - test

before_script:
  - /bin/true
script:
  - /bin/true

jobs:
  include:
    - stage: unit
      if: branch = master OR type = pull_request
      services: []
      before_script:
        - echo "Linting"
      script: /bin/true
      name: lint
    - script: echo "Unit"
      services: []
      before_script: []
      name: unit
      env: KUBE=none

    - stage: Publishing
      if: branch = master OR (type = pull_request AND head_repo = repo)
      install: []
      before_script: []
      before_deploy:
        - git fetch --unshallow
        - git rev-list --first-parent --count HEAD
        - /bin/true
      script: echo "Publishing image/chart"
      deploy:
        provider: script
        script:
          echo "deploy make publish-image deploy-helm-repo..."
        skip_cleanup: true
        on:
          branch: master
